using System.Collections.Generic;

namespace CScan.Whitelist
{
    internal class DriverWhitelist
    {
        private static readonly Dictionary<string, string> whitelist = new Dictionary<string, string>
        {
            {@"C:\Windows\system32\drivers\1394ohci.sys", "1394 OHCI Compliant Host Controller"},
            {@"C:\Windows\system32\drivers\3ware.sys", "3ware"},
            {@"C:\Windows\system32\drivers\ACPI.sys", "Microsoft ACPI Driver"},
            {@"C:\Windows\system32\drivers\acpials.sys", "ALS Sensor Filter"},
            {@"C:\Windows\system32\drivers\AcpiDev.sys", "ACPI Devices driver"},
            {@"C:\Windows\system32\Drivers\acpiex.sys", "Microsoft ACPIEx Driver"},
            {@"C:\Windows\system32\drivers\acpipagr.sys", "ACPI Processor Aggregator Driver"},
            {@"C:\Windows\system32\drivers\acpipmi.sys", "ACPI Power Meter Driver"},
            {@"C:\Windows\system32\drivers\acpitime.sys", "ACPI Wake Alarm Driver"},
            {@"C:\Windows\system32\drivers\ADP80XX.SYS", "ADP80XX"},
            {@"C:\Windows\system32\drivers\afd.sys", "Ancillary Function Driver for Winsock"},
            {@"C:\Windows\system32\drivers\AgileVpn.sys (WAN Miniport", "IKEv2)"},
            {@"C:\Windows\system32\DRIVERS\ahcache.sys", "Application Compatibility Cache"},
            {@"C:\Windows\system32\drivers\amdk8.sys", "AMD K8 Processor Driver"},
            {@"C:\Windows\system32\drivers\amdppm.sys", "AMD Processor Driver"},
            {@"C:\Windows\system32\drivers\amdsata.sys", "amdsata"},
            {@"C:\Windows\system32\drivers\amdsbs.sys", "amdsbs"},
            {@"C:\Windows\system32\drivers\amdxata.sys", "amdxata"},
            {@"C:\Windows\system32\drivers\appid.sys", "AppID Driver"},
            {@"C:\Windows\system32\drivers\applockerfltr.sys", "Smartlocker Filter Driver"},
            {@"C:\Windows\system32\drivers\AppvStrm.sys", "AppvStrm"},
            {@"C:\Windows\system32\drivers\AppvVemgr.sys", "AppvVemgr"},
            {@"C:\Windows\system32\drivers\AppvVfs.sys", "AppvVfs"},
            {@"C:\Windows\system32\drivers\arcsas.sys", "Adaptec SAS/SATA-II RAID Storport's Miniport Driver"},
            {@"C:\Windows\system32\drivers\asyncmac.sys", "RAS Asynchronous Media Driver"},
            {@"C:\Windows\system32\drivers\atapi.sys", "IDE Channel"},
            {@"C:\Windows\system32\DRIVERS\awealloc.sys", "AWE Memory Allocation Driver"},
            {@"C:\Windows\system32\drivers\b57nd60a.sys", "Broadcom NetXtreme Gigabit Ethernet - NDIS 6.0"},
            {@"C:\Windows\system32\drivers\BasicDisplay.sys", "BasicDisplay"},
            {@"C:\Windows\system32\drivers\BasicRender.sys", "BasicRender"},
            {@"C:\Windows\system32\drivers\bcmfn.sys", "bcmfn Service"},
            {@"C:\Windows\system32\drivers\bcmfn2.sys", "bcmfn2 Service"},
            {@"C:\Windows\system32\DRIVERS\bcmwl63a.sys", "Broadcom 802.11 Network Adapter Driver"},
            {@"C:\Windows\system32\drivers\Beep.sys", "Beep"},
            {@"C:\Windows\system32\DRIVERS\bowser.sys", "Browser Support Driver"},
            {@"C:\Windows\system32\drivers\bridge.sys", "Microsoft MAC Bridge"},
            {@"C:\Windows\system32\drivers\bScsiSDa.sys", "bScsiSDa"},
            {@"C:\Windows\system32\drivers\BthA2DP.sys", "Bluetooth Stereo"},
            {@"C:\Windows\system32\drivers\BthAvrcpTg.sys", "Bluetooth Audio/Video Remote Control HID"},
            {@"C:\Windows\system32\drivers\BthEnum.sys", "Bluetooth Enumerator Service"},
            {@"C:\Windows\system32\DRIVERS\BthHfAud.sys", "Bluetooth Hands-Free"},
            {@"C:\Windows\system32\drivers\bthhfenum.sys", "Bluetooth Hands-Free Audio and Call Control HID Enumerator"},
            {@"C:\Windows\system32\drivers\BthHFHid.sys", "Bluetooth Hands-Free Call Control HID"},
            {@"C:\Windows\system32\drivers\BthLEEnum.sys", "Bluetooth Low Energy Driver"},
            {@"C:\Windows\system32\drivers\bthmodem.sys", "Bluetooth Modem Communications Driver"},
            {@"C:\Windows\system32\drivers\bthpan.sys (Bluetooth Device", "Personal Area Network)"},
            {@"C:\Windows\system32\drivers\BTHport.sys", "Bluetooth Port Driver"},
            {@"C:\Windows\system32\drivers\BTHUSB.sys", "Bluetooth Radio USB Driver"},
            {@"C:\Windows\system32\drivers\buttonconverter.sys", "Service for Portable Device Control devices"},
            {@"C:\Windows\system32\drivers\bxvbda.sys", "QLogic Network Adapter VBD"},
            {@"C:\Windows\system32\drivers\capimg.sys", "HID driver for CapImg touch screen"},
            {@"C:\Windows\system32\DRIVERS\cdfs.sys", "CD/DVD File System Reader"},
            {@"C:\Windows\system32\drivers\cdrom.sys", "CD-ROM Driver"},
            {@"C:\Windows\system32\drivers\cht4sx64.sys", "cht4iscsi"},
            {@"C:\Windows\system32\drivers\cht4vx64.sys", "Chelsio Virtual Bus Driver"},
            {@"C:\Windows\system32\drivers\circlass.sys", "Consumer IR Devices"},
            {@"C:\Windows\system32\drivers\CLFS.sys (Common Log", "CLFS)"},
            {@"C:\Windows\system32\drivers\CmBatt.sys", "Microsoft ACPI Control Method Battery Driver"},
            {@"C:\Windows\system32\Drivers\cng.sys", "CNG"},
            {@"C:\Windows\system32\DRIVERS\cnghwassist.sys", "CNG Hardware Assist algorithm provider"},
            {@"C:\Windows\system32\drivers\condrv.sys", "Console Driver"},
            {@"C:\Windows\system32\DRIVERS\CS420x64.sys", "CS420xLowerFilter"},
            {@"C:\Windows\system32\drivers\csc.sys", "Offline Files Driver"},
            {@"C:\Windows\system32\drivers\dam.sys", "Desktop Activity Moderator Driver"},
            {@"C:\Windows\system32\drivers\dc1-controller.sys", "Xbox Peripherals Driver"},
            {@"C:\Windows\system32\Drivers\dfsc.sys", "DFS Namespace Client Driver"},
            {@"C:\Windows\system32\drivers\disk.sys", "Disk Driver"},
            {@"C:\Windows\system32\drivers\dmvsc.sys", "dmvsc"},
            {@"C:\Windows\system32\DRIVERS\drmkaud.sys", "Microsoft Trusted Audio Drivers"},
            {@"C:\Windows\system32\drivers\dxgkrnl.sys", "LDDM Graphics Subsystem"},
            {@"C:\Windows\system32\drivers\EhStorClass.sys", "Enhanced Storage Filter Driver"},
            {@"C:\Windows\system32\drivers\EhStorTcgDrv.sys", "Microsoft driver for storage devices supporting IEEE 1667 and TCG protocols"},
            {@"C:\Windows\system32\drivers\ElcMouLFlt.sys", "ELECOM USB Mouse Lower Filter Driver"},
            {@"C:\Windows\system32\drivers\ElcMouUFlt.sys", "ELECOM USB Mouse Upper Filter Driver"},
            {@"C:\Windows\system32\drivers\errdev.sys", "Microsoft Hardware Error Device Driver"},
            {@"C:\Windows\system32\drivers\evbda.sys", "QLogic 10 Gigabit Ethernet Adapter VBD"},
            {@"C:\Windows\system32\drivers\exfat.sys", "exFAT File System Driver"},
            {@"C:\Windows\system32\drivers\fastfat.sys", "FAT12/16/32 File System Driver"},
            {@"C:\Windows\system32\drivers\fdc.sys", "Floppy Disk Controller Driver"},
            {@"C:\Windows\system32\drivers\filecrypt.sys", "FileCrypt"},
            {@"C:\Windows\system32\drivers\fileinfo.sys", "File Information FS MiniFilter"},
            {@"C:\Windows\system32\drivers\filetrace.sys", "Filetrace"},
            {@"C:\Windows\system32\drivers\flpydisk.sys", "Floppy Disk Driver"},
            {@"C:\Windows\system32\drivers\fltmgr.sys", "FltMgr"},
            {@"C:\Windows\system32\drivers\FsDepends.sys", "File System Dependency Minifilter"},
            {@"C:\Windows\system32\drivers\ftdibus.sys", "USB Serial Converter Driver"},
            {@"C:\Windows\system32\drivers\ftser2k.sys", "USB Serial Port Driver"},
            {@"C:\Windows\system32\DRIVERS\fvevol.sys", "BitLocker Drive Encryption Filter Driver"},
            {@"C:\Windows\system32\DRIVERS\fwndislwf64.sys", "Emsisoft NDIS packet filter"},
            {@"C:\Windows\system32\drivers\genericusbfn.sys", "Generic USB Function Class"},
            {@"C:\Windows\system32\drivers\gpuenergydrv.sys", "GPU Energy Driver"},
            {@"C:\Windows\system32\drivers\HDAudBus.sys", "Microsoft UAA Bus Driver for High Definition Audio"},
            {@"C:\Windows\system32\DRIVERS\HdAudio.sys", "Microsoft 1.1 UAA Function Driver for High Definition Audio Service"},
            {@"C:\Windows\system32\drivers\HidBatt.sys", "HID UPS Battery Driver"},
            {@"C:\Windows\system32\drivers\hidbth.sys", "Microsoft Bluetooth HID Miniport"},
            {@"C:\Windows\system32\drivers\hidi2c.sys", "Microsoft I2C HID Miniport Driver"},
            {@"C:\Windows\system32\drivers\hidinterrupt.sys", "Common Driver for HID Buttons implemented with interrupts"},
            {@"C:\Windows\system32\drivers\hidir.sys", "Microsoft Infrared HID Driver"},
            {@"C:\Windows\system32\drivers\hidusb.sys", "Microsoft HID Class Driver"},
            {@"C:\Windows\system32\drivers\HpSAMD.sys", "HpSAMD"},
            {@"C:\Windows\system32\drivers\HTTP.sys", "HTTP Service"},
            {@"C:\Windows\system32\drivers\hvservice.sys", "Hypervisor/Virtual Machine Support Driver"},
            {@"C:\Windows\system32\drivers\hwpolicy.sys", "Hardware Policy Driver"},
            {@"C:\Windows\system32\drivers\hyperkbd.sys", "hyperkbd"},
            {@"C:\Windows\system32\drivers\i8042prt.sys", "i8042 Keyboard and PS/2 Mouse Port Driver"},
            {@"C:\Windows\system32\drivers\iagpio.sys", "Intel Serial IO GPIO Controller Driver"},
            {@"C:\Windows\system32\drivers\iai2c.sys", "Intel(R) Serial IO I2C Host Controller"},
            {@"C:\Windows\system32\drivers\iaLPSS_GPIO.sys", "Intel(R) Serial IO GPIO Driver"},
            {@"C:\Windows\system32\drivers\iaLPSS_I2C.sys", "Intel(R) Serial IO I2C Driver"},
            {@"C:\Windows\system32\drivers\iaLPSS_SPI.sys", "Intel(R) Serial IO SPI Driver"},
            {@"C:\Windows\system32\drivers\iaLPSS_UART.sys", "Intel(R) Serial IO UART Driver"},
            {@"C:\Windows\system32\drivers\iaLPSS2i_GPIO2.sys", "Intel(R) Serial IO GPIO Driver v2"},
            {@"C:\Windows\system32\drivers\iaLPSS2i_I2C.sys", "Intel(R) Serial IO I2C Driver v2"},
            {@"C:\Windows\system32\drivers\iaLPSSi_GPIO.sys", "Intel(R) Serial IO GPIO Controller Driver"},
            {@"C:\Windows\system32\drivers\iaLPSSi_I2C.sys", "Intel(R) Serial IO I2C Controller Driver"},
            {@"C:\Windows\system32\drivers\iaStorAV.sys", "Intel(R) SATA RAID Controller Windows"},
            {@"C:\Windows\system32\drivers\iaStorV.sys", "Intel RAID Controller Windows 7"},
            {@"C:\Windows\system32\drivers\ibbus.sys (Mellanox InfiniBand Bus/AL", "Filter Driver)"},
            {@"C:\Windows\system32\DRIVERS\imdisk.sys", "ImDisk Virtual Disk Driver"},
            {@"C:\Windows\system32\drivers\IndirectKmd.sys", "Indirect Displays Kernel-Mode Driver"},
            {@"C:\Windows\system32\drivers\intelide.sys", "intelide"},
            {@"C:\Windows\system32\drivers\intelpep.sys", "Intel(R) Power Engine Plug-in Driver"},
            {@"C:\Windows\system32\drivers\intelppm.sys", "Intel Processor Driver"},
            {@"C:\Windows\system32\drivers\iorate.sys", "iorate"},
            {@"C:\Windows\system32\DRIVERS\ipfltdrv.sys", "IP Traffic Filter Driver"},
            {@"C:\Windows\system32\drivers\IPMIDrv.sys", "IPMIDRV"},
            {@"C:\Windows\system32\drivers\ipnat.sys", "IP Network Address Translator"},
            {@"C:\Windows\system32\drivers\irda.sys", "irda"},
            {@"C:\Windows\system32\drivers\irenum.sys", "IR Bus Enumerator"},
            {@"C:\Windows\system32\drivers\isapnp.sys", "isapnp"},
            {@"C:\Windows\system32\drivers\isocusb.sys", "isocusb"},
            {@"C:\Windows\system32\drivers\kbdclass.sys", "Keyboard Class Driver"},
            {@"C:\Windows\system32\drivers\kbdhid.sys", "Keyboard HID Driver"},
            {@"C:\Windows\system32\drivers\kdnic.sys (Microsoft Kernel Debug Network Miniport", "NDIS 6.20)"},
            {@"C:\Windows\system32\drivers\KeyMagic.sys", "USB Keyboard HID Filter"},
            {@"C:\Windows\system32\Drivers\ksecdd.sys", "KSecDD"},
            {@"C:\Windows\system32\Drivers\ksecpkg.sys", "KSecPkg"},
            {@"C:\Windows\system32\drivers\ksthunk.sys", "Kernel Streaming Thunks"},
            {@"C:\Windows\system32\drivers\lltdio.sys", "Link-Layer Topology Discovery Mapper I/O Driver"},
            {@"C:\Windows\system32\drivers\lsi_sas.sys", "LSI_SAS"},
            {@"C:\Windows\system32\drivers\lsi_sas2i.sys", "LSI_SAS2i"},
            {@"C:\Windows\system32\drivers\lsi_sas3i.sys", "LSI_SAS3i"},
            {@"C:\Windows\system32\drivers\lsi_sss.sys", "LSI_SSS"},
            {@"C:\Windows\system32\drivers\luafv.sys", "UAC File Virtualization"},
            {@"C:\Windows\system32\drivers\lxss.sys", "lxss"},
            {@"C:\Windows\system32\drivers\MB3SwissArmy.sys", "MB3SwissArmy"},
            {@"C:\Windows\system32\drivers\megasas.sys", "megasas"},
            {@"C:\Windows\system32\drivers\MegaSas2i.sys", "megasas2i"},
            {@"C:\Windows\system32\drivers\megasr.sys", "megasr"},
            {@"C:\Windows\system32\drivers\mlx4_bus.sys", "Mellanox ConnectX Bus Enumerator"},
            {@"C:\Windows\system32\drivers\mmcss.sys", "Multimedia Class Scheduler"},
            {@"C:\Windows\system32\drivers\modem.sys", "Modem"},
            {@"C:\Windows\system32\drivers\monitor.sys", "Microsoft Monitor Class Function Driver Service"},
            {@"C:\Windows\system32\drivers\mouclass.sys", "Mouse Class Driver"},
            {@"C:\Windows\system32\drivers\mouhid.sys", "Mouse HID Driver"},
            {@"C:\Windows\system32\drivers\mountmgr.sys", "Mount Point Manager"},
            {@"C:\Windows\system32\drivers\mpsdrv.sys", "Windows Firewall Authorization Driver"},
            {@"C:\Windows\system32\drivers\mrxdav.sys", "WebDav Client Redirector Driver"},
            {@"C:\Windows\system32\DRIVERS\mrxsmb.sys", "SMB MiniRedirector Wrapper and Engine"},
            {@"C:\Windows\system32\DRIVERS\mrxsmb10.sys", "SMB 1.x MiniRedirector"},
            {@"C:\Windows\system32\DRIVERS\mrxsmb20.sys", "SMB 2.0 MiniRedirector"},
            {@"C:\Windows\system32\drivers\Msfs.sys", "Msfs"},
            {@"C:\Windows\system32\Drivers\msgpioclx.sys", "Microsoft GPIO Class Extension Driver"},
            {@"C:\Windows\system32\drivers\msgpiowin32.sys", "Common Driver for Buttons, DockMode and Laptop/Slate Indicator"},
            {@"C:\Windows\system32\Drivers\mshidkmdf.sys", "Pass-through HID to KMDF Filter Driver"},
            {@"C:\Windows\system32\drivers\mshidumdf.sys", "Pass-through HID to UMDF Driver"},
            {@"C:\Windows\system32\drivers\msisadrv.sys", "msisadrv"},
            {@"C:\Windows\system32\drivers\msiscsi.sys", "iScsiPort Driver"},
            {@"C:\Windows\system32\DRIVERS\MSKSSRV.sys", "Microsoft Streaming Service Proxy"},
            {@"C:\Windows\system32\drivers\mslldp.sys", "Microsoft Link-Layer Discovery Protocol"},
            {@"C:\Windows\system32\DRIVERS\MSPCLOCK.sys", "Microsoft Streaming Clock Proxy"},
            {@"C:\Windows\system32\DRIVERS\MSPQM.sys", "Microsoft Streaming Quality Manager Proxy"},
            {@"C:\Windows\system32\drivers\MsRPC.sys", "MsRPC"},
            {@"C:\Windows\system32\drivers\mssecflt.sys", "Microsoft Security Events Component Minifilter"},
            {@"C:\Windows\system32\drivers\mssmbios.sys", "Microsoft System Management BIOS Driver"},
            {@"C:\Windows\system32\DRIVERS\MSTEE.sys", "Microsoft Streaming Tee/Sink-to-Sink Converter"},
            {@"C:\Windows\system32\drivers\MTConfig.sys", "Microsoft Input Configuration Driver"},
            {@"C:\Windows\system32\Drivers\mup.sys", "Mup"},
            {@"C:\Windows\system32\drivers\mvumis.sys", "mvumis"},
            {@"C:\Windows\system32\drivers\ndfltr.sys", "NetworkDirect Service"},
            {@"C:\Windows\system32\drivers\ndis.sys", "NDIS System Driver"},
            {@"C:\Windows\system32\drivers\ndiscap.sys", "Microsoft NDIS Capture"},
            {@"C:\Windows\system32\drivers\NdisImPlatform.sys", "Microsoft Network Adapter Multiplexor Protocol"},
            {@"C:\Windows\system32\DRIVERS\ndistapi.sys", "Remote Access NDIS TAPI Driver"},
            {@"C:\Windows\system32\drivers\ndisuio.sys", "NDIS Usermode I/O Protocol"},
            {@"C:\Windows\system32\drivers\NdisVirtualBus.sys", "Microsoft Virtual Network Adapter Enumerator"},
            {@"C:\Windows\system32\drivers\ndiswan.sys", "Remote Access NDIS WAN Driver"},
            {@"C:\Windows\system32\DRIVERS\ndiswan.sys", "Remote Access LEGACY NDIS WAN Driver"},
            {@"C:\Windows\system32\drivers\Ndu.sys", "Windows Network Data Usage Monitoring Driver"},
            {@"C:\Windows\system32\drivers\NetAdapterCx.sys", "Network Adapter Wdf Class Extension Library"},
            {@"C:\Windows\system32\drivers\netbios.sys", "NetBIOS Interface"},
            {@"C:\Windows\system32\DRIVERS\netbt.sys", "NetBT"},
            {@"C:\Windows\system32\drivers\Npfs.sys", "Npfs"},
            {@"C:\Windows\system32\drivers\npsvctrig.sys", "Named pipe service trigger provider"},
            {@"C:\Windows\system32\drivers\nsiproxy.sys", "NSI Proxy Service Driver"},
            {@"C:\Windows\system32\drivers\NTFS.sys", "NTFS"},
            {@"C:\Windows\system32\drivers\Null.sys", "Null"},
            {@"C:\Windows\system32\drivers\nvhda64v.sys", "Service for NVIDIA High Definition Audio Driver"},
            {@"C:\Windows\system32\drivers\nvraid.sys", "nvraid"},
            {@"C:\Windows\system32\drivers\nvstor.sys", "nvstor"},
            {@"C:\Windows\system32\DRIVERS\nwifi.sys", "NativeWiFi Filter"},
            {@"C:\Windows\system32\drivers\pacer.sys", "QoS Packet Scheduler"},
            {@"C:\Windows\system32\drivers\parport.sys", "Parallel port driver"},
            {@"C:\Windows\system32\drivers\partmgr.sys", "Partition driver"},
            {@"C:\Windows\system32\drivers\pci.sys", "PCI Bus Driver"},
            {@"C:\Windows\system32\drivers\pciide.sys", "pciide"},
            {@"C:\Windows\system32\drivers\pcmcia.sys", "pcmcia"},
            {@"C:\Windows\system32\drivers\pcw.sys", "Performance Counters for Windows Driver"},
            {@"C:\Windows\system32\drivers\pdc.sys", "pdc"},
            {@"C:\Windows\system32\drivers\peauth.sys", "PEAUTH"},
            {@"C:\Windows\system32\drivers\percsas2i.sys", "percsas2i"},
            {@"C:\Windows\system32\drivers\percsas3i.sys", "percsas3i"},
            {@"C:\Windows\system32\drivers\processr.sys", "Processor Driver"},
            {@"C:\Windows\system32\drivers\qwavedrv.sys", "QWAVE driver"},
            {@"C:\Windows\system32\DRIVERS\rasacd.sys", "Remote Access Auto Connection Driver"},
            {@"C:\Windows\system32\drivers\rasl2tp.sys (WAN Miniport", "L2TP)"},
            {@"C:\Windows\system32\DRIVERS\raspppoe.sys", "Remote Access PPPOE Driver"},
            {@"C:\Windows\system32\drivers\raspptp.sys (WAN Miniport", "PPTP)"},
            {@"C:\Windows\system32\drivers\rassstp.sys (WAN Miniport", "SSTP)"},
            {@"C:\Windows\system32\DRIVERS\rdbss.sys", "Redirected Buffering Sub System"},
            {@"C:\Windows\system32\drivers\rdpbus.sys", "Remote Desktop Device Redirector Bus Driver"},
            {@"C:\Windows\system32\drivers\rdpdr.sys", "Remote Desktop Device Redirector Driver"},
            {@"C:\Windows\system32\drivers\rdpvideominiport.sys", "Remote Desktop Video Miniport Driver"},
            {@"C:\Windows\system32\drivers\rdyboost.sys", "ReadyBoost"},
            {@"C:\Windows\system32\drivers\ReFSv1.sys", "ReFSv1"},
            {@"C:\Windows\system32\drivers\registry.sys", "Virtual Registry for Containers"},
            {@"C:\Windows\system32\drivers\rfcomm.sys (Bluetooth Device", "RFCOMM Protocol TDI)"},
            {@"C:\Windows\system32\drivers\rspndr.sys", "Link-Layer Topology Discovery Responder"},
            {@"C:\Windows\system32\drivers\sbp2port.sys", "SBP-2 Transport/Protocol Bus Driver"},
            {@"C:\Windows\system32\DRIVERS\scfilter.sys", "Smart card PnP Class Filter Driver"},
            {@"C:\Windows\system32\drivers\scmbus.sys", "Microsoft Storage Class Memory Bus Driver"},
            {@"C:\Windows\system32\drivers\scmdisk0101.sys", "Microsoft NVDIMM-N disk driver"},
            {@"C:\Windows\system32\drivers\sdstor.sys", "SD Storage Port Driver"},
            {@"C:\Windows\system32\Drivers\Sentinel64.sys", "Sentinel64"},
            {@"C:\Windows\system32\drivers\SerCx.sys", "Serial UART Support Library"},
            {@"C:\Windows\system32\drivers\SerCx2.sys", "Serial UART Support Library"},
            {@"C:\Windows\system32\drivers\serenum.sys", "Serenum Filter Driver"},
            {@"C:\Windows\system32\drivers\serial.sys", "Serial port driver"},
            {@"C:\Windows\system32\drivers\sermouse.sys", "Serial Mouse Driver"},
            {@"C:\Windows\system32\drivers\sfloppy.sys", "High-Capacity Floppy Disk Drive"},
            {@"C:\Windows\system32\drivers\SiSRaid2.sys", "SiSRaid2"},
            {@"C:\Windows\system32\drivers\sisraid4.sys", "SiSRaid4"},
            {@"C:\Windows\system32\drivers\spaceport.sys", "Storage Spaces Driver"},
            {@"C:\Windows\system32\drivers\SpbCx.sys", "Simple Peripheral Bus Support Library"},
            {@"C:\Windows\system32\DRIVERS\srv.sys", "Server SMB 1.xxx Driver"},
            {@"C:\Windows\system32\DRIVERS\srv2.sys", "Server SMB 2.xxx Driver"},
            {@"C:\Windows\system32\drivers\storahci.sys", "Microsoft Standard SATA AHCI Driver"},
            {@"C:\Windows\system32\drivers\stornvme.sys", "Microsoft Standard NVM Express Driver"},
            {@"C:\Windows\system32\drivers\storqosflt.sys", "Storage QoS Filter Driver"},
            {@"C:\Windows\system32\drivers\storufs.sys (Microsoft Universal Flash Storage", "UFS) Driver"},
            {@"C:\Windows\system32\drivers\storvsc.sys", "storvsc"},
            {@"C:\Windows\system32\drivers\swenum.sys", "Software Bus Driver"},
            {@"C:\Windows\system32\drivers\Synth3dVsc.sys", "Synth3dVsc"},
            {@"C:\Windows\system32\DRIVERS\t_mouse.sys", "HID-compliand device"},
            {@"C:\Windows\system32\drivers\tcpip.sys", "TCP/IP Protocol Driver"},
            {@"C:\Windows\system32\drivers\tcpipreg.sys", "TCP/IP Registry Compatibility"},
            {@"C:\Windows\system32\DRIVERS\tdx.sys", "NetIO Legacy TDI Support Driver"},
            {@"C:\Windows\system32\DRIVERS\TeeDriverx64.sys", "Intel(R) Management Engine Interface "},
            {@"C:\Windows\system32\drivers\terminpt.sys", "Microsoft Remote Desktop Input Driver"},
            {@"C:\Windows\system32\drivers\tinspusb.sys", "TI-Nspire(TM) Handheld or TI Network Bridge Device Driver"},
            {@"C:\Windows\system32\drivers\tpm.sys", "TPM"},
            {@"C:\Windows\system32\drivers\TsUsbFlt.sys", "Remote Desktop USB Hub Class Filter Driver"},
            {@"C:\Windows\system32\drivers\TsUsbGD.sys", "Remote Desktop Generic USB Device"},
            {@"C:\Windows\system32\drivers\tsusbhub.sys", "Remote Desktop USB Hub"},
            {@"C:\Windows\system32\drivers\tunnel.sys", "Microsoft Tunnel Miniport Adapter Driver"},
            {@"C:\Windows\system32\drivers\uaspstor.sys (USB Attached SCSI", "UAS) Driver"},
            {@"C:\Windows\system32\Drivers\UcmCx.sys", "USB Connector Manager KMDF Class Extension"},
            {@"C:\Windows\system32\Drivers\UcmTcpciCx.sys", "UCM-TCPCI KMDF Class Extension"},
            {@"C:\Windows\system32\drivers\UcmUcsi.sys", "USB Connector Manager UCSI Client"},
            {@"C:\Windows\system32\drivers\ucx01000.sys", "USB Host Support Library"},
            {@"C:\Windows\system32\drivers\udecx.sys", "USB Device Emulation Support Library"},
            {@"C:\Windows\system32\DRIVERS\udfs.sys", "udfs"},
            {@"C:\Windows\system32\drivers\UEFI.sys", "Microsoft UEFI Driver"},
            {@"C:\Windows\system32\drivers\UevAgentDriver.sys", "UevAgentDriver"},
            {@"C:\Windows\system32\drivers\ufx01000.sys", "USB Function Class Extension"},
            {@"C:\Windows\system32\drivers\UfxChipidea.sys", "USB Chipidea Controller"},
            {@"C:\Windows\system32\drivers\ufxsynopsys.sys", "USB Synopsys Controller"},
            {@"C:\Windows\system32\drivers\umbus.sys", "UMBus Enumerator Driver"},
            {@"C:\Windows\system32\drivers\umpass.sys", "Microsoft UMPass Driver"},
            {@"C:\Windows\system32\drivers\urschipidea.sys", "Chipidea USB Role-Switch Driver"},
            {@"C:\Windows\system32\drivers\urscx01000.sys", "USB Role-Switch Support Library"},
            {@"C:\Windows\system32\drivers\urssynopsys.sys", "Synopsys USB Role-Switch Driver"},
            {@"C:\Windows\system32\drivers\usbaudio.sys (USB Audio Driver", "WDM)"},
            {@"C:\Windows\system32\drivers\usbccgp.sys", "Microsoft USB Generic Parent Driver"},
            {@"C:\Windows\system32\drivers\usbcir.sys (eHome Infrared Receiver", "USBCIR)"},
            {@"C:\Windows\system32\drivers\usbehci.sys", "Microsoft USB 2.0 Enhanced Host Controller Miniport Driver"},
            {@"C:\Windows\system32\drivers\usbhub.sys", "Microsoft USB Standard Hub Driver"},
            {@"C:\Windows\system32\drivers\UsbHub3.sys", "SuperSpeed Hub"},
            {@"C:\Windows\system32\drivers\usbohci.sys", "Microsoft USB Open Host Controller Miniport Driver"},
            {@"C:\Windows\system32\drivers\usbprint.sys", "Microsoft USB PRINTER Class"},
            {@"C:\Windows\system32\drivers\usbser.sys", "Microsoft USB Serial Driver"},
            {@"C:\Windows\system32\drivers\USBSTOR.SYS", "USB Mass Storage Driver"},
            {@"C:\Windows\system32\drivers\usbuhci.sys", "Microsoft USB Universal Host Controller Miniport Driver"},
            {@"C:\Windows\system32\Drivers\usbvideo.sys (USB Video Device", "WDM)"},
            {@"C:\Windows\system32\drivers\USBXHCI.SYS", "USB xHCI Compliant Host Controller"},
            {@"C:\Windows\system32\drivers\vdrvroot.sys", "Microsoft Virtual Drive Enumerator"},
            {@"C:\Windows\system32\drivers\VerifierExt.sys", "VerifierExt"},
            {@"C:\Windows\system32\drivers\vhdmp.sys", "vhdmp"},
            {@"C:\Windows\system32\drivers\vhf.sys (Virtual HID Framework", "VHF) Driver"},
            {@"C:\Windows\system32\drivers\vmbus.sys", "Virtual Machine Bus"},
            {@"C:\Windows\system32\drivers\VMBusHID.sys", "VMBusHID"},
            {@"C:\Windows\system32\drivers\vmgencounter.sys", "Microsoft Hyper-V Generation Counter"},
            {@"C:\Windows\system32\drivers\vmgid.sys", "Microsoft Hyper-V Guest Infrastructure Driver"},
            {@"C:\Windows\system32\drivers\vms3cap.sys", "s3cap"},
            {@"C:\Windows\system32\drivers\vmstorfl.sys", "Microsoft Hyper-V Storage Accelerator"},
            {@"C:\Windows\system32\drivers\volmgr.sys", "Volume Manager Driver"},
            {@"C:\Windows\system32\drivers\volmgrx.sys", "Dynamic Volume Manager"},
            {@"C:\Windows\system32\drivers\volsnap.sys", "Volume Shadow Copy driver"},
            {@"C:\Windows\system32\drivers\volume.sys", "Volume driver"},
            {@"C:\Windows\system32\drivers\vpci.sys", "Microsoft Hyper-V Virtual PCI Bus"},
            {@"C:\Windows\system32\drivers\vsmraid.sys", "vsmraid"},
            {@"C:\Windows\system32\drivers\vstxraid.sys", "VIA StorX Storage RAID Controller Windows Driver"},
            {@"C:\Windows\system32\drivers\vtss.sys", "vtss"},
            {@"C:\Windows\system32\drivers\vwifibus.sys", "Virtual Wireless Bus Driver"},
            {@"C:\Windows\system32\drivers\vwififlt.sys", "Virtual WiFi Filter Driver"},
            {@"C:\Windows\system32\drivers\vwifimp.sys", "Virtual WiFi Miniport Service"},
            {@"C:\Windows\system32\drivers\wacompen.sys", "Wacom Serial Pen HID Driver"},
            {@"C:\Windows\system32\DRIVERS\wanarp.sys", "Remote Access IPv6 ARP Driver"},
            {@"C:\Windows\system32\drivers\wcifs.sys", "Windows Container Isolation"},
            {@"C:\Windows\system32\drivers\wcnfs.sys", "Windows Container Name Virtualization"},
            {@"C:\Windows\system32\drivers\WdBoot.sys", "Windows Defender Boot Driver"},
            {@"C:\Windows\system32\drivers\Wdf01000.sys", "Kernel Mode Driver Frameworks service"},
            {@"C:\Windows\system32\drivers\WdFilter.sys", "Windows Defender Mini-Filter Driver"},
            {@"C:\Windows\system32\DRIVERS\wdiwifi.sys", "WDI Driver Framework"},
            {@"C:\Windows\system32\Drivers\WdNisDrv.sys", "Windows Defender Network Inspection System Driver"},
            {@"C:\Windows\system32\drivers\wfplwfs.sys", "Microsoft Windows Filtering Platform"},
            {@"C:\Windows\system32\drivers\wimmount.sys", "WIMMount"},
            {@"C:\Windows\system32\drivers\WindowsTrustedRT.sys", "Windows Trusted Execution Environment Class Extension"},
            {@"C:\Windows\system32\drivers\WindowsTrustedRTProxy.sys", "Microsoft Windows Trusted Runtime Secure Service"},
            {@"C:\Windows\system32\drivers\windrvr6.sys", "WinDriver6"},
            {@"C:\Windows\system32\drivers\winmad.sys", "WinMad Service"},
            {@"C:\Windows\system32\drivers\WinUSB.SYS", "WinUSB - Kernel Driver 02/10/2017 6.1.7600.16385"},
            {@"C:\Windows\system32\drivers\winverbs.sys", "WinVerbs Service"},
            {@"C:\Windows\system32\drivers\wmiacpi.sys", "Microsoft Windows Management Interface for ACPI"},
            {@"C:\Windows\system32\drivers\Wof.sys", "Windows Overlay File System Filter Driver"},
            {@"C:\Windows\system32\drivers\WpdUpFltr.sys", "WPD Upper Class Filter Driver"},
            {@"C:\Windows\system32\drivers\ws2ifsl.sys", "Winsock IFS Driver"},
            {@"C:\Windows\system32\drivers\WSDPrint.sys", "WSD Print Support"},
            {@"C:\Windows\system32\DRIVERS\WSDScan.sys", "WSD Scan Support"},
            {@"C:\Windows\system32\drivers\WudfPf.sys", "User Mode Driver Frameworks Platform Driver"},
            {@"C:\Windows\system32\drivers\WudfRd.sys", "WUDFRd"},
            {@"C:\Windows\system32\drivers\xboxgip.sys", "Xbox Game Input Protocol Driver"},
            {@"C:\Windows\system32\drivers\xinputhid.sys", "XINPUT HID Filter Driver"},
        };

        public static bool IsWhitelisted(string key, string value)
        {
            if (whitelist.ContainsKey(key) && whitelist[key] == value)
            {
                return Authenticode.IsSigned(key);
            }

            return false;
        }
    }
}